variables:
  CONTAINER_NAME: $CI_PROJECT_NAME
  DEPLOY_PACKAGE_DIR_BASE: $CI_PROJECT_NAME

include:
  - project: 'commons/ci-templates'
    ref: v1.2.0
    file:
      - 'gitlab-default-stages.yml'
      - 'gitlab-nfpm-pack.yml'
      - 'gitlab-deploy.yml'


build:
  image: ubuntu:20.04
  stage: build
  artifacts:
    paths:
      - bin/
      - variables
      - README.md
      - CHANGELOG.md
  script:
    - export LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 DEBIAN_FRONTEND=noninteractive
    - sed -i -Ee 's/http:\/\/(archive|security)/mirror:\/\/mirrors/' -e 's/\/ubuntu\//\/mirrors.txt/' /etc/apt/sources.list
    - apt update
    - apt -yq --no-install-recommends install locales ca-certificates
    - locale-gen en_US.UTF-8
    - apt install -yq --no-install-recommends g++ gcc make git
    - .gitlab-ci/build.sh
    - echo export PACKAGE_VERSION="$(git describe --tags)" >> variables
    - echo export PACKAGE_VERSION_SHORT="$(git describe --tags --abbrev=0)" >> variables
